### ISSUE TITLE
Organization of introduction to OSF

### ISSUE THREAD

**Issue by evomellor** [csoderberg/OSF-Curriculum#17]
The current structure of the intro section is as follows: 1) ideal scientific process, 2) intro to reproducibility crisis 3) definitions of reproducibility, etc 4) causes of low reproducibility 5) consequences of low reproducibility 6) what's going to happen in workshop, 7) split into groups of 3

I propose the following organization: 1) compare ideal to actual scientific processes 2) incentives that scientists face cause this misalignment between ideals and actual processes  3) why the actual processes lead to low reproducibility 4) reproducibility crisis and definitions 5) how the OSF fits into the actual process of science in order to facilitate a more ideal/open process 6) what's going to happen in this workshop 7) assessment activity in groups of 3

**Comment by csoderberg** [comment]
A lot of the incentive structure stuff actually relates more to pre-reg, power, HARKing, stats, than to workflow documentation per se etc., which aren't covered in these sections (by design they aren't covered, may create separate modules for them; And I realize that HARKing and pre-reg are related to documentation, but they aren't specifically discussed. They are mentioned in passing, but not fully explained). So, the incentives leading to misalignment would leave a lot of loose ends that aren't covered in the workshop, which is why I didn't include them.

**Comment by csoderberg** [comment]
Also, because different fields tend to use the term 'reproducibility' very differently, I think it's important to define as earlier as possible what we're talking about when we say reproducibility. Because 'why the actual processes lead to low reproducibility' doesn't make sense unless everyone knows what are mean when you say 'reproducibility'
